### ISSUE TITLE
Remove small allocation workaround

### ISSUE THREAD

**Issue by bigerl** [dice-group/metall-ffi#11]
- [ ] report bug in metall
- [ ] once patched&released, update to the most recent version and remove the workaround in tests_Sanity.cpp

> This was failing, apparently metall cannot allocate objects that small. This has nothing to do with the update, has been this way even in 0.23.1

_Originally posted by @Clueliss in https://github.com/dice-group/metall-ffi/pull/10#discussion_r1696944752_

**Comment by Clueliss** [comment]
The culprit was the custom chunk size, I've reverted it to default in #10
